apiVersion: v1
kind: Service
metadata:
  name: simple-webserver-py-service
  labels: 
    name: simple-webserver-py-service
    app: simple-webserver-py-app
spec:
  type: LoadBalancer
  ports:
  - port:  80
    targetPort: 5000
  selector:
    name: simple-webserver-py-pod
    app: simple-webserver-py-app