apiVersion: v1
kind: Service
metadata:
  name: helloworld-py-service
  labels: 
    name: helloworld-py-service
    app: helloworld-py-app
spec:
  type: LoadBalancer
  ports:
  - port:  80
    targetPort: 5000
  selector:
    name: helloworld-py-pod
    app: helloworld-py-app